source 'https://rubygems.org'


gem 'rails', '4.2.5.1'

gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'
gem 'httparty'
gem 'faker'
gem 'active_model_serializers'
gem 'normalize_url'

gem 'sidekiq'
gem 'sinatra', :require => nil

gem 'factory_girl_rails', '~> 4.2.1'

gem 'rack-cors', :require => 'rack/cors'

group :development, :test do
  gem 'rspec-rails', '~> 3.4.0'
  gem 'rspec-activemodel-mocks'
  gem "fakeredis", require: "fakeredis/rspec"
end